<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>NomadFramework.Audio.FMOD</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nomad.Audio\Nomad.Audio.csproj" />
    <ProjectReference Include="..\Nomad.ResourceCache\Nomad.ResourceCache.csproj" />
  </ItemGroup>

  <ItemGroup>
    <NomadNativeAsset Include="fmod.dll" HostOS="Windows" RuntimeIdentifier="win-x64" />
    <NomadNativeAsset Include="fmodL.dll" HostOS="Windows" RuntimeIdentifier="win-x64" />
    <NomadNativeAsset Include="fmodstudio.dll" HostOS="Windows" RuntimeIdentifier="win-x64" />
    <NomadNativeAsset Include="fmodstudioL.dll" HostOS="Windows" RuntimeIdentifier="win-x64" />

    <NomadNativeAsset Include="fmod.so" HostOS="Linux" RuntimeIdentifier="linux-x64" />
    <NomadNativeAsset Include="fmodL.so" HostOS="Linux" RuntimeIdentifier="linux-x64" />
    <NomadNativeAsset Include="libfmod.so" HostOS="Linux" RuntimeIdentifier="linux-x64" />
    <NomadNativeAsset Include="libfmodL.so" HostOS="Linux" RuntimeIdentifier="linux-x64" />
    <NomadNativeAsset Include="libfmodstudio.so" HostOS="Linux" RuntimeIdentifier="linux-x64" />
    <NomadNativeAsset Include="libfmodstudioL.so" HostOS="Linux" RuntimeIdentifier="linux-x64" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>
</Project>