<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Build Configuration -->
    <TargetFrameworks>net10.0</TargetFrameworks>
    <Nullable>annotations</Nullable>
    <IsPackable>false</IsPackable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1812</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Benchly" />
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);EVENT_DEBUG</DefineConstants>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Source\Nomad.FileSystem\Nomad.FileSystem.csproj" />
    <ProjectReference Include="..\Source\Nomad.Save\Nomad.Save.csproj" />
    <ProjectReference Include="..\Source\Nomad.Events\Nomad.Events.csproj" />
    <ProjectReference Include="..\Source\Nomad.Input\Nomad.Input.csproj" />
    <ProjectReference Include="..\Source\Nomad.OnlineServices.Steam\Nomad.OnlineServices.Steam.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="steam_appid.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DefaultConfig.json">
      <Link>Assets/Config/Bindings/DefaultBinds.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Reference Include="Steamworks.NET">
      <HintPath>Steamworks.NET.dll</HintPath>
    </Reference>
    <Content Condition="'$(IsLinux)' == 'true'" Include="libsteam_api.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
    <Content Condition="'$(IsLinux)' == 'true'" Include="steam_api.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </Content>
  </ItemGroup>

</Project>
