<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>NomadFramework.Console</PackageId>
    <UseNomadSourceGenerators>true</UseNomadSourceGenerators>
    <NoWarn>$(NoWarn);CA1308</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nomad.Core\Nomad.Core.csproj" />
    <ProjectReference Include="..\Nomad.Logger\Nomad.Logger.csproj" />
    <ProjectReference Include="..\Nomad.CVars\Nomad.CVars.csproj" />
    <ProjectReference Include="..\Nomad.Events\Nomad.Events.csproj" />
  </ItemGroup>
</Project>