<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>NomadFramework.Events</PackageId>
    <EnableEventDebug>true</EnableEventDebug>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nomad.Core\Nomad.Core.csproj" />
  </ItemGroup>
</Project>