<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>NomadFramework.FileSystem</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nomad.Core\Nomad.Core.csproj" />
    <ProjectReference Include="..\Nomad.Events\Nomad.Events.csproj" />
    <ProjectReference Include="..\Nomad.Logger\Nomad.Logger.csproj" />
    <ProjectReference Include="..\Nomad.CVars\Nomad.CVars.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Compression" />
  </ItemGroup>
</Project>