<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>NomadFramework.EngineUtils.Godot</PackageId>
    <UseNomadSourceGenerators>true</UseNomadSourceGenerators>
    <LinkNomadEngineTemplates>true</LinkNomadEngineTemplates>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nomad.ResourceCache\Nomad.ResourceCache.csproj" />
    <ProjectReference Include="..\Nomad.CVars\Nomad.CVars.csproj" />
    <ProjectReference Include="..\Nomad.Console\Nomad.Console.csproj" />
    <ProjectReference Include="..\Nomad.Core\Nomad.Core.csproj" />
    <ProjectReference Include="..\Nomad.Events\Nomad.Events.csproj" />
    <ProjectReference Include="..\Nomad.EngineTemplates\Nomad.EngineTemplates.csproj" />
  </ItemGroup>
</Project>