<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>NomadFramework.EngineUtils.Unity</PackageId>
    <Version>0.1.0-alpha1</Version>

    <EmitCompilerGeneratedFiles Condition="'$(Configuration)' == 'Debug'">true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath Condition="'$(Configuration)' == 'Debug'">$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nomad.CVars\Nomad.CVars.csproj" />
    <ProjectReference Include="..\Nomad.Core\Nomad.Core.csproj" />
    <ProjectReference Include="..\Nomad.Events\Nomad.Events.csproj" />
  </ItemGroup>
</Project>