name: Documentation

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    name: Build Doxygen Docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Doxygen and Graphviz
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
    
    - name: Generate Doxygen Documentation
      run: doxygen Doxyfile
    
    - name: add nojekyll marker
      run: touch doxygen-output/html/.nojekyll
    
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: doxygen-output/html
  
  deploy-docs:
    name: Deploy GitHub Pages
    needs: build-docs
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ setps.deployment.outputs.pages_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
